= ComboCtl

This is code for controlling and communicating with the Accu-Chek Spirit Combo, written in Kotlin.

WARNING: This project is in the alpha state.



== Disclaimer and warning

IMPORTANT: This project is intended purely for research. Any attempts
at using this project for accessing and operating medical equipment
in a non certified way are _NOT_ supported. This document comes without
warranty or formal support of *ANY* kind. **USE AT YOUR OWN RISK**.

IMPORTANT: All product and company names, trademarks, servicemarks, registered
trademarks, and registered servicemarks are the property of their respective
holders. Their use is for information purposes and does not imply any affiliation
with or endorsement by them.



== Overview

ComboCtl implements functionality for generating and parsing data sent to and
received from the Combo. Currently, the following modules exist:

* *comboctl* - The base library. It includes core functionality for pairing,
  setting up connections, running the communication with the Combo etc. It also
  contains platform specific bits, like bindings to a platform's Bluetooth stack.
  This module is set up as a Kotlin/Multiplatform subproject. It currently
  supports the JVM and Android as targets, though Native may be added later.
* *javafxApp* - JavaFX 8 based test application to operate Combo pumps.
  Includes a UI to see the Combo's display frames.
* *androidApp* - Android test application to operate Combo pumps.

ComboCtl is primarily implemented in Kotlin. Platform specific bits may be written
in other languages.

To use ComboCtl in other projects, only the code in the `comboctl` subproject
is necessary.

NOTE: ComboCtl makes heavy use of https://kotlinlang.org/docs/reference/coroutines-overview.html[Kotlin Coroutines]. Be sure to understand how to
use them to be able to make sense of the ComboCtl API.



=== Communication specification

The reverse engineered communication protocols and procedures are documented in
<<docs/combo-comm-spec.adoc#,the Combo communication specification document>>.


=== Main API

The main class to use is `PumpManager`. It allows for discovering and pairing
with Combo pumps, and creates instances of the `Pump` class. This class is the
second primary class to use. It provides access to a particular pump (specified
by its Bluetooth address).

Integration requires that the user implements the following bits:

* Persistent pump state store backend: For each Combo pump, a small
  dataset needs to be kept stored in a persistent fashion. When
  pairing with a pump, a new store is set up. The pairing process
  will fill this store with data that will not change after pairing
  (cipher keys etc). The store will also contain a nonce that will
  be changed every time a data packet is sent to the Combo. See the
  `PersistentPumpStateStore` class for details.
* Logger backend: By default, a platform specific logger backend
  is used. For example, on Android, that backend uses the
  `android.util.Log` function for logging. It is not necessary that
  the user defines a custom logger backend, but it is recommended
  for a more seamless integration if the application that ComboCtl
  gets integrated into uses its own logging framework.
* Bluetooth interface: `PumpManager` expects an objec that implements
  the `BluetoothInterface` interface. On Linux, there is the
  `BlueZInterface` class for this purpose.



== Project structure


=== comboctl/

This is the base library. It is structured like a typical Kotlin/Multiplatform
library. The directory structure goes as follows:

* `comboctl/src/` - Base source directory
* `comboctl/src/linuxBlueZCpp/` - static C++ library for operating BlueZ, the
  Linux Bluetooth stack
* `comboctl/src/commonMain/` - Core ComboCtl code, platform independent
* `comboctl/src/jvmMain/` - JVM specific bits such as the BlueZ based
  Bluetooth bindings and platform specific logging functionality
* `comboctl/src/jvmMain/cpp/linuxBlueZCppJNI/` - C++ library for interfacing
  linuxBlueZCpp with the JVM via the JNI
* `comboctl/src/jvmTest/` - Unit tests for the core functionality, using JUnit 5
* `comboctl/src/androidMain/` - Android specific bits such as the Bluetooth
  bindings and platform specific logging functionality (only basic bits are
  implemented here so far)

The unit tests are kept in `comboctl/src/jvmTest/` to be able to run
them easily on the PC. In the future, additional unit tests with
Android dependencies may be added too, in a new `comboctl/src/androidTest/`
subdirectory.


=== javafxApp/

This is a JavaFX 8 based application to operate Combo pumps interactively.
It consists of a main window with a list of all paired pumps and controls
for initiating discovery and pairing. For each paired pump, a dedicated pump
window can be opened by clicking on the pump's Bluetooth address in the
list in the main window. This pump window contains buttons for simulating
Combo button presses and for connecting/disconnecting/unpairing (the last
one is not implemented yet in the application). The pump window also contains
a JavaFX ImageView for showing the display frames sent by the Combo.

This application can be started by running: `./gradlew :javafxApp:run`

On HiDPI screens, setting the `GDK_SCALE` environment variable in Linux
can be used to zoom the user interface. `GDK_SCALE=2.0` zooms the UI
by a factor of 2, for example.

The Gradle build scripts are set up to skip javafxApp automatically when
building for a non-PC platform, most notably Android.


=== androidApp/

This is a simple test Android app to connect to a single pump. It features
an RT display frame view and several controls to perform typical actions
like up, down, etc.



== Prerequisites

To build ComboCtl with IDEA or Android Studio, make sure that Kotlin 1.5.31
support is installed. Preinstalled Kotlin plugins may not be up to date.

On Android Studio, also install the KMM plugin.

To build the linuxBlueZCpp library, C headers and libraries for GLib 2.0
are needed. On Ubuntu, run: `apt install libglib2.0-dev`

Make sure that `pkg-config` is installed.

To build the linuxBlueZCppJNI library, the JNI needs to be installed.
On Ubuntu, run: `apt install default-jdk`



== Building

ComboCtl is built using Gradle.

To build with the command line and run the unit tests, run:

  ./gradlew build

The project can also be imported into Android Studio and Intellij IDEA. Simply
open/import this project's root directory.

Note that this builds _all_ modules, including the JavaFX application,
development tools, and C++ bindings. It is also possible to build specific
subprojects. For example, to just build the C++ JNI bindings (and their
dependencies), run:

  ./gradlew :comboctl:src:jvmMain:cpp:linuxBlueZCppJNI:build

Look into `settings.gradle.kts` for the list of subprojects.



== Contributing

Before opening a pull request please make sure to run

  ./gradlew ktlintCheck

Many issues like ordering imports alphabetically can be resolved automatically with:

  ./gradlew ktlintFormat


== TODO

* Integrate the [detekt static analyzer](https://detekt.github.io/detekt/)
  in addition to ktlint may be useful.
* Try to figure out the remaining TODOs in combo-comm-spec.adoc.
* Thorough testing to cover all sorts of use cases.
